name: geoponto
description: "Sistema Profissional de Ponto Digital Georreferenciado"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Agora alinhado corretamente
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- FIREBASE ---
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

  # --- GEOLOCALIZAÇÃO ---
  geolocator: ^11.0.0
  latlong2: ^0.9.1 

  # --- MAPAS ---
  flutter_map: ^6.1.0

  # --- OFFLINE E ARQUIVOS ---
  sqflite: ^2.3.0
  path: ^1.9.0

  # --- UTILITÁRIOS ---
  intl: ^0.20.2 # Versão atualizada para bater com o seu Flutter
  device_info_plus: ^10.1.0

  # --- ESTADO ---
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true