name: geoponto_pro
description: "App de registro de ponto com geolocalização, assinatura digital e notificações"
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- FIREBASE ---
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.1.0
  firebase_messaging: ^15.2.0       # Notificações Push

  # --- GERENCIAMENTO DE ESTADO ---
  flutter_riverpod: ^2.5.1

  # --- GEOLOCALIZAÇÃO E MAPAS ---
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_map: ^7.0.2               # Versão mais atual e estável
  latlong2: ^0.9.1

  # --- NOTIFICAÇÕES LOCAIS E AGENDAMENTO ---
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.4

  # --- PDF E IMPRESSÃO ---
  pdf: ^3.11.0
  printing: ^5.12.0
  path_provider: ^2.1.3

  # --- BANCO DE DADOS LOCAL E PREFERÊNCIAS ---
  sqflite: ^2.3.3+1
  shared_preferences: ^2.3.0

  # --- UTILITÁRIOS E UI ---
  signature: ^5.4.0                 # Assinatura digital
  intl: ^0.20.2                     # Internacionalização (datas/moedas)
  uuid: ^4.4.0                      # Gerador de IDs únicos
  permission_handler: ^11.3.1       # Controle de permissões de GPS/Notif
  device_info_plus: ^10.1.0         # Identificação do aparelho
  csv: ^6.0.0            # Para transformar listas em formato CSV
  share_plus: ^7.2.2     # Para abrir a janela de compartilhamento (e-mail, WhatsApp, etc)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # --- GERADORES DE ÍCONE E SPLASH ---
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

# --- CONFIGURAÇÃO DO ÍCONE DO APP ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#f0fdf4" # Um fundo verde bem clarinho para destacar o vidro
  adaptive_icon_foreground: "assets/images/logo.png"

# --- CONFIGURAÇÃO DA TELA DE SPLASH (ABERTURA) ---
flutter_native_splash:
  color: "#15803D" # O verde principal do seu app
  image: "assets/images/logo.png"
  android_12:
    image: "assets/images/logo.png"
    color: "#15803D"
  fullscreen: true