// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAebuCRidXzrZmfrdJfQ0fRwpBjKTWlBbk',
    appId: '1:803247449375:web:b488c83e8b319316463c2a',
    messagingSenderId: '803247449375',
    projectId: 'geopontopro',
    authDomain: 'geopontopro.firebaseapp.com',
    storageBucket: 'geopontopro.firebasestorage.app',
    measurementId: 'G-RGKKB78ZW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJq9U49QX1xOg31bHWA1GtBq22rmFD-Jo',
    appId: '1:803247449375:android:b90090e956138917463c2a',
    messagingSenderId: '803247449375',
    projectId: 'geopontopro',
    storageBucket: 'geopontopro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAVLEyb8ui3t9-Agzm2kCOjqpRVAcTl2s',
    appId: '1:803247449375:ios:6749db85b59c5dcf463c2a',
    messagingSenderId: '803247449375',
    projectId: 'geopontopro',
    storageBucket: 'geopontopro.firebasestorage.app',
    iosBundleId: 'com.example.geoponto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAVLEyb8ui3t9-Agzm2kCOjqpRVAcTl2s',
    appId: '1:803247449375:ios:6749db85b59c5dcf463c2a',
    messagingSenderId: '803247449375',
    projectId: 'geopontopro',
    storageBucket: 'geopontopro.firebasestorage.app',
    iosBundleId: 'com.example.geoponto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAebuCRidXzrZmfrdJfQ0fRwpBjKTWlBbk',
    appId: '1:803247449375:web:db440cee8d23cd48463c2a',
    messagingSenderId: '803247449375',
    projectId: 'geopontopro',
    authDomain: 'geopontopro.firebaseapp.com',
    storageBucket: 'geopontopro.firebasestorage.app',
    measurementId: 'G-E4D2BSCTWN',
  );

}